name: Setup ansible
description: Sets up ansible for further use in the workflow.
author: karafra@karafra.net

inputs:
  ssh_private_key:
    description: SSH private key for accessing the target servers.
    required: true
  server_hosts:
    description: Comma-separated hostnames or IPs of the target servers.
    required: true
  ssh_user:
    description: SSH user for accessing the target servers.
    required: true

runs:
  using: composite
  steps:
    - name: Install Ansible
      shell: bash
      # language=bash
      run: |
        sudo apt update
        sudo apt install -y ansible sshpass

    - name: Prepare SSH key
      shell: bash
      # language=bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Add each host to known_hosts automatically
        IFS=',' read -ra HOSTS <<< "${{ inputs.server_hosts }}"
        for host in "${HOSTS[@]}"; do
          ssh-keyscan -H "$host" >> ~/.ssh/known_hosts 2>/dev/null || true
        done

    - name: Create dynamic YAML inventory
      uses: actions/github-script@v7
      # language=javascript
      with:
        script: |
          const fs = require('fs');
          
          // Get inputs
          const serverHosts = '${{ inputs.server_hosts }}'.split(',').map(h => h.trim());
          const sshUser = '${{ inputs.ssh_user }}';
          
          // Generate server entries using template literals
          const serverEntries = serverHosts
              .map((host, index) => {
                  const serverNum = index + 1;
                  return `        server${serverNum}:\n          ansible_host: ${host}\n          ansible_user: ${sshUser}`;
              })
              .join('\n');
          
          // Generate complete YAML
          const yamlContent = `all:
          vars:
            ansible_connection: ssh
            ansible_port: 22
            ansible_user: ${sshUser}
            ansible_ssh_private_key_file: ~/.ssh/id_rsa
            ansible_become_method: sudo
            k3s_cluster_name: homelab
            k3s_version: latest
            k3s_channel: stable
            enable_argocd: true
          children:
            dedicated_servers:
              hosts:
            ${serverEntries}
            k3s_cluster:
              hosts: {}
          `;
            
            // Write to file
            fs.writeFileSync('inventory.yml', yamlContent);
            
            console.log('Generated inventory.yml:');
            console.log(yamlContent);
